[tool.poetry]
name = "cell-abm-pipeline"
version = "0.0.0"
description = "ARCADE workflows."
authors = [
    "Jessica S. Yu <jesyu@uw.edu>"
]
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
prefect = "^2.6.0"
hydra-core = "^1.2.0"
numpy = "^1.22.0"
tifffile = ">=2021.8.30"
imagecodecs = "2021.4.28"
matplotlib = "3.5.1"
aicsimageio = "4.6.3"
simulariumio = "1.4.1"
scikit-image = "0.19.2"
jupyter = "^1.0.0"
jupyterlab = "^3.3.0"
aicsshparam = "^0.1.1"
boto3 = "^1.21.16"
trimesh = {extras = ["shapely"], version = "^3.10.2"}
Shapely = "^1.8.1"
quilt3 = "^5.0.0"
hexalattice = "^1.2.1"
click = ">=8.0.0"
s3fs = "^2022.3.0"
io_collection = { path = "../io-collection/", develop = true }
abm_initialization_collection = { path = "../abm-initialization-collection/", develop = true }
tabulate = "^0.9.0"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
pylint = "^2.15.2"
tox = "^3.26.0"
pytest = "^7.1.3"
pytest-cov = "^3.0.0"
pytest-subtests = "^0.8.0"
Sphinx = "^5.1.1"
mypy = "^0.971"
sphinx-rtd-theme = "^1.0.0"
sphinx_mdinclude = "^0.5.2"

[tool.poetry.scripts]
abmpipe = "cell_abm_pipeline.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
