[tool.poetry]
name = "cell-abm-pipeline"
version = "0.0.0"
description = "Cell ABM workflows."
authors = [
    "Jessica S. Yu <jesyu@uw.edu>"
]
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
prefect = "^2.6.0"
hydra-core = "^1.2.0"
tabulate = "^0.9.0"
io-collection = "^0.5.0"
container-collection = "^0.4.3"
arcade-collection = "^0.4.0"
abm-initialization-collection = "^0.2.0"
abm-shape-collection = "^0.1.0"
abm-colony-collection = "^0.1.0"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
pylint = "^2.15.2"
tox = "^3.26.0"
pytest = "^7.2.0"
pytest-cov = "^3.0.0"
pytest-subtests = "^0.8.0"
Sphinx = "^5.1.1"
mypy = "^0.971"
sphinx-rtd-theme = "^1.0.0"
sphinx_mdinclude = "^0.5.2"

[tool.poetry.scripts]
abmpipe = "cell_abm_pipeline.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
