[tool.poetry]
name = "cell_abm_pipeline"
version = "0.0.0"
description = ""
authors = ["jessicasyu <jesyu@uw.edu>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.22.0"
tifffile = ">=2021.8.30"
imagecodecs = "2021.4.28"
matplotlib = "3.5.1"
aicsimageio = "4.6.3"
simulariumio = "1.4.1"
scikit-image = "0.19.2"
jupyter = "^1.0.0"
jupyterlab = "^3.3.0"
aicsshparam = "^0.1.1"
boto3 = "^1.21.16"
trimesh = {extras = ["shapely"], version = "^3.10.2"}
Shapely = "^1.8.1"
quilt3 = "^5.0.0"
hexalattice = "^1.2.1"
click = ">=8.0.0"
s3fs = "^2022.3.0"

[tool.poetry.dev-dependencies]
tox = "^3.25.0"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-subtests = "^0.8.0"
pylint = "^2.14.1"
black = "^22.3.0"
Sphinx = "^4.1.1"
mypy = "^0.961"
sphinx-rtd-theme = "^1.0.0"
sphinx_mdinclude = "^0.5.1"

[tool.poetry.scripts]
basic-metrics = "cell_abm_pipeline.basic_metrics.__main__:cli"
resource-usage = "cell_abm_pipeline.resource_usage.__main__:cli"
cell-shape = "cell_abm_pipeline.cell_shape.__main__:cli"
colony-dynamics = "cell_abm_pipeline.colony_dynamics.__main__:cli"
initial-conditions = "cell_abm_pipeline.initial_conditions.__main__:cli"
convert-format = "cell_abm_pipeline.convert_format.__main__:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
