name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black mypy

    - name: Lint with pylint
      run: |
        pylint --ignore-patterns=test.*?py src/ tests/ --fail-under=7.0

    - name: Check with black
      run: |
        black -l 100 --check src/ tests/

    - name: Check with mypy
      run: |
        mypy --config-file mypy.ini src
