name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black

    - name: Lint with pylint
      run: |
        python lint.py --path ./src --threshold 7.0

    - name: Check with black
      run: |
        black --check src/ tests/
